import turtle
def Guia():
    l=turtle.Turtle()
    l.hideturtle
    l.speed(100)
    l.penup()
    l.goto(-325,290)
    l.pendown()
    for i in range(2):    
        l.forward(650)
        l.left(90)
        l.forward(45)
        l.left(90)
    l.penup()
    l.goto(0,300)
    l.pendown()
    l.write("La conspiracion del Reino Geometrico", False, "center", ("Comic sans",20))
    l.fillcolor("lightblue")
    l.begin_fill()
    l.penup()
    l.goto(-350,-150)
    l.pendown()
    for i in range(2):
        l.forward(700)
        l.left(90)
        l.forward(430)
        l.left(90)
    l.end_fill()
    l.fillcolor("green")
    l.begin_fill()
    l.penup()
    l.goto(-350,-150)
    l.pendown()
    for i in range(2):
        l.forward(700)
        l.left(90)
        l.forward(150)
        l.left(90)
    l.end_fill()
    l.penup()
    l.goto(-325,-175)
    l.pendown()
    for i in range(2):
        l.forward(650)
        l.right(90)
        l.forward(150)
        l.right(90)
    l.penup()
    l.goto(280,280)
    l.pendown()
    l.fillcolor("yellow")
    l.begin_fill()
    l.right(90)
    l.circle(80,180)
    l.end_fill()
    t=turtle.Turtle()
    t.hideturtle()
    t.speed(50)
    t.penup()
    t.goto(-50,175)
    t.pendown()
    for i in range(5):
        t.fillcolor("white")
        t.begin_fill()
        t.circle(40, 90)  # Dibujar un cuarto de círculo
        t.left(90)
        t.forward(80)  
        t.end_fill()
def circulo():
        i=60
        x=200
        y=0
        v=turtle.Turtle()
        v.hideturtle
        v.speed(100)
        v.pensize(3)
        v.fillcolor(color)
        v.begin_fill()
        v.penup()
        v.goto(x,y)
        v.pendown()
        v.circle(i)
        v.end_fill()
        v.penup()
        v.goto(x-i,y+i)
        v.pendown()
        v.right(135)#315
        v.forward(30) #si le cambias lo grande le cambias este valor, solo es el largo del brazo
        v.fillcolor(color)
        v.begin_fill()
        v.circle(10)
        v.end_fill()
        v.penup()
        v.goto(x+i,y+i)
        v.pendown()
        v.left(90)
        v.forward(30)
        v.left(180)
        v.fillcolor(color)
        v.begin_fill()
        v.circle(10)
        v.end_fill()
        v.penup()
        v.setheading(270)
        v.goto(x+30,y+10)
        v.pendown()
        v.forward(50)
        v.fillcolor(color)
        v.begin_fill()
        for i in range(2):
            v.left(90)
            v.forward(30)
            v.left(90)
            v.forward(10)
        v.end_fill()
        v.penup()
        v.setheading(270)
        v.goto(x-30,y+10)
        v.pendown()
        v.forward(50)
        v.fillcolor(color)
        v.begin_fill()
        for i in range(2):
            v.right(90)
            v.forward(30)
            v.right(90)
            v.forward(10)
        v.end_fill()
def cuadrado():
    x=100
    y=0
    turtle.hideturtle
    turtle.speed(50)
    turtle.penup()
    turtle.goto(x,y) 
    turtle.pendown()
    turtle.pensize(3)
    turtle.fillcolor("darkgreen")
    turtle.begin_fill()  
    for i in range(4):
        turtle.forward(120)
        turtle.left(90)
    turtle.end_fill()
    def dibujar_pies():
        turtle.penup()
        turtle.goto(x+30,y) 
        turtle.pendown()
        turtle.setheading(270)
        turtle.forward(30)
        for i in range(2):
            turtle.fillcolor("darkgreen")
            turtle.begin_fill()
            turtle.forward(10)
            turtle.right(90)
            turtle.forward(30)
            turtle.right(90)
            turtle.end_fill()
        turtle.penup()
        turtle.goto(x+90,y) 
        turtle.pendown()
        turtle.setheading(270)
        turtle.forward(30)
        for i in range(2):
            turtle.fillcolor("darkgreen")
            turtle.begin_fill()
            turtle.forward(10)
            turtle.left(90)
            turtle.forward(30)
            turtle.left(90)
            turtle.end_fill() 
    dibujar_pies()
    def dibujar_manos():
        turtle.penup()
        turtle.goto(x,y+60) 
        turtle.setheading(240)
        turtle.pendown()
        turtle.forward(30)
        turtle.fillcolor("darkgreen")
        turtle.begin_fill()
        for i in range(4):
            turtle.forward(20)
            turtle.right(90)
        turtle.end_fill()
        turtle.penup()
        turtle.goto(x+120,y+60) 
        turtle.setheading(300)
        turtle.pendown()
        turtle.forward(30)
        turtle.fillcolor("darkgreen")
        turtle.begin_fill()
        for i in range(4):
            turtle.forward(20)
            turtle.left(90)
        turtle.end_fill()
    turtle.end_fill()
    dibujar_manos()
def hexagono():
    x=-100
    y=0
    t=turtle.Turtle()
    t.hideturtle()
    t.speed(50)
    t.penup()
    t.goto(x,y) 
    t.setheading(180)
    t.pendown()
    t.pensize(3)
    t.fillcolor("blue")
    t.begin_fill()
    for i in range(6):
        t.forward(70)
        t.right(60)
    t.end_fill()
    def dibujar_manos():
        t.penup()
        t.goto(x-105,y+60) 
        t.setheading(240)
        t.pendown()
        t.forward(30)
        t.fillcolor("blue")
        t.begin_fill()
        for i in range(6):
            t.forward(20)
            t.right(60)
        t.end_fill()
        t.penup()
        t.goto(x+35,y+60) 
        t.setheading(300)
        t.pendown()
        t.forward(30)
        t.fillcolor("blue")
        t.begin_fill()
        for i in range(6):
            t.forward(20)
            t.left(60)
        t.end_fill()
    dibujar_manos()
    def dibujar_pies():
        t.penup()
        t.goto(x-60,y) 
        t.pendown()
        t.setheading(270)
        t.forward(30)
        for i in range(2):
            t.fillcolor("blue")
            t.begin_fill()
            t.forward(10)
            t.right(90)
            t.forward(30)
            t.right(90)
            t.end_fill()
        t.penup()
        t.goto(x-10,y) 
        t.pendown()
        t.setheading(270)
        t.forward(30)
        for i in range(2):
            t.fillcolor("blue")
            t.begin_fill()
            t.forward(10)
            t.left(90)
            t.forward(30)
            t.left(90)
            t.end_fill() 
    dibujar_pies()
def hexagono_pequeño():
    x=-250
    y=-100
    t=turtle.Turtle()
    t.hideturtle()
    t.speed(50)
    t.penup()
    t.goto(x,y) 
    t.setheading(180)
    t.pendown()
    t.pensize(3)
    t.fillcolor("blue")
    t.begin_fill()
    for i in range(6):
        t.forward(25)
        t.right(60)
    t.end_fill()
    def dibujar_manos():
        t.penup()
        t.goto(x-38,y+20) 
        t.setheading(240)
        t.pendown()
        t.forward(10)
        t.fillcolor("blue")
        t.begin_fill()
        for i in range(6):
            t.forward(10)
            t.right(60)
        t.end_fill()
        t.penup()
        t.goto(x+13,y+20) 
        t.setheading(300)
        t.pendown()
        t.forward(10)
        t.fillcolor("blue")
        t.begin_fill()
        for i in range(6):
            t.forward(10)
            t.left(60)
        t.end_fill()
    dibujar_manos()
    def dibujar_pies():
        t.penup()
        t.goto(x-18,y) 
        t.pendown()
        t.setheading(270)
        t.forward(10)
        for i in range(2):
            t.fillcolor("blue")
            t.begin_fill()
            t.forward(5)
            t.right(90)
            t.forward(15)
            t.right(90)
            t.end_fill()
        t.penup()
        t.goto(x-8,y) 
        t.pendown()
        t.setheading(270)
        t.forward(10)
        for i in range(2):
            t.fillcolor("blue")
            t.begin_fill()
            t.forward(5)
            t.left(90)
            t.forward(15)
            t.left(90)
            t.end_fill() 
    dibujar_pies()
def castillo():
    c=turtle.Turtle()
    c.hideturtle()
    c.speed(50)
    c.width(5)
    c.penup()
    c.goto(-300,-100)
    c.pendown()
    c.fillcolor("gray")
    c.begin_fill()
    for i in range(2):
          c.forward(150)
          c.left(90)
          c.forward(300)
          c.left(90)
    c.end_fill()
    c.fillcolor("gray")
    c.begin_fill()
    c.forward(150)
    for i in range(2):
        c.forward(300)
        c.left(90)
        c.forward(150)
        c.left(90)
    c.end_fill()
    c.forward(300)
    c.fillcolor("gray")
    c.begin_fill()
    for i in range(2):
          c.forward(150)
          c.left(90)
          c.forward(300)
          c.left(90)
    c.end_fill()
    c.penup()
    c.goto(-300,200)
    c.pendown()
    c.fillcolor("red")
    c.begin_fill()
    c.forward(150)
    c.setheading(150)
    c.forward(90)
    c.setheading(210)
    c.forward(85)
    c.end_fill()
    c.penup()
    c.goto(150,200)
    c.pendown()
    c.fillcolor("red")
    c.begin_fill()
    c.setheading(360)
    c.forward(150)
    c.setheading(150)
    c.forward(90)
    c.setheading(210)
    c.forward(85)
    c.end_fill()
def Dibujo_de_panel1():
    Guia()
    castillo()
    def circulo_pequeño():
            i=20
            x=0
            y=-100
            v=turtle.Turtle()
            v.hideturtle()
            v.speed(100)
            v.pensize(3)
            v.fillcolor(color)
            v.begin_fill()
            v.penup()
            v.goto(x,y)
            v.pendown()
            v.circle(i)
            v.end_fill()
            v.penup()
            v.goto(x-i,y+i)
            v.pendown()
            v.right(135)#315
            v.forward(15) #si le cambias lo grande le cambias este valor, solo es el largo del brazo
            v.fillcolor(color)
            v.begin_fill()
            v.circle(5)
            v.end_fill()
            v.penup()
            v.goto(x+i,y+i)
            v.pendown()
            v.left(90)
            v.forward(15)
            v.left(180)
            v.fillcolor(color)
            v.begin_fill()
            v.circle(5)
            v.end_fill()
            v.penup()
            v.setheading(270)
            v.goto(x+10,y+2)
            v.pendown()
            v.forward(15)
            v.fillcolor(color)
            v.begin_fill()
            for i in range(2):
                v.left(90)
                v.forward(15)
                v.left(90)
                v.forward(5)
            v.end_fill()
            v.penup()
            v.setheading(270)
            v.goto(x-10,y+2)
            v.pendown()
            v.forward(15)
            v.fillcolor(color)
            v.begin_fill()
            for i in range(2):
                v.right(90)
                v.forward(15)
                v.right(90)
                v.forward(5)
            v.end_fill()
    circulo_pequeño()
    def cuadrado_pequeño():
        x=-100
        y=-100
        turtle.hideturtle
        turtle.speed(50)
        turtle.penup()
        turtle.goto(x,y) 
        turtle.pendown()
        turtle.pensize(3)
        turtle.fillcolor("darkgreen")
        turtle.begin_fill()  
        turtle.setheading(90)
        for i in range(4):
            turtle.forward(40)
            turtle.left(90)
        turtle.end_fill()
        def dibujar_pies():
            turtle.penup()
            turtle.goto(x-30,y) 
            turtle.pendown()
            turtle.setheading(270)
            turtle.forward(10)
            for i in range(2):
                turtle.fillcolor("darkgreen")
                turtle.begin_fill()
                turtle.forward(5)
                turtle.right(90)
                turtle.forward(15)
                turtle.right(90)
                turtle.end_fill()
            turtle.penup()
            turtle.goto(x-10,y) 
            turtle.pendown()
            turtle.setheading(270)
            turtle.forward(10)
            for i in range(2):
                turtle.fillcolor("darkgreen")
                turtle.begin_fill()
                turtle.forward(5)
                turtle.left(90)
                turtle.forward(15)
                turtle.left(90)
                turtle.end_fill() 
        dibujar_pies()
        def dibujar_manos():
            turtle.penup()
            turtle.goto(x-40,y+20) 
            turtle.setheading(240)
            turtle.pendown()
            turtle.forward(15)
            turtle.fillcolor("darkgreen")
            turtle.begin_fill()
            for i in range(4):
                turtle.forward(8)
                turtle.right(90)
            turtle.end_fill()
            turtle.penup()
            turtle.goto(x,y+20) 
            turtle.setheading(300)
            turtle.pendown()
            turtle.forward(15)
            turtle.fillcolor("darkgreen")
            turtle.begin_fill()
            for i in range(4):
                turtle.forward(8)
                turtle.left(90)
            turtle.end_fill()
        turtle.end_fill()
        dibujar_manos()
    cuadrado_pequeño()
    def triangulo_pequeño():
        x=100
        y=-100
        turtle.hideturtle()
        turtle.speed(50)
        turtle.penup()
        turtle.goto(x,y) 
        turtle.pendown()
        turtle.pensize(3)
        turtle.fillcolor("yellow")
        turtle.begin_fill()
        turtle.setheading(360)
        for i in range(3):
            turtle.forward(44)
            turtle.left(120)
        turtle.end_fill()
        turtle.penup()
        turtle.goto(x+11,y) 
        turtle.pendown()
        turtle.setheading(270)
        turtle.forward(15)
        for i in range(2):
            turtle.fillcolor("yellow")
            turtle.begin_fill()
            turtle.forward(5)
            turtle.right(90)
            turtle.forward(15)
            turtle.right(90)
            turtle.end_fill()
        turtle.penup()
        turtle.goto(x+33,y) 
        turtle.pendown()
        turtle.setheading(270)
        turtle.forward(15)
        for i in range(2):
            turtle.fillcolor("yellow")
            turtle.begin_fill()
            turtle.forward(5)
            turtle.left(90)
            turtle.forward(15)
            turtle.left(90)
            turtle.end_fill()
        turtle.penup()
        turtle.goto(x+9,y+15) 
        turtle.pendown()
        turtle.setheading(190)
        turtle.forward(10)
        turtle.setheading(180)
        turtle.fillcolor("yellow")
        turtle.begin_fill()
        for i in range(3):
            turtle.forward(15)
            turtle.left(120)
        turtle.end_fill()
        turtle.penup()
        turtle.goto(x+36,y+15) 
        turtle.pendown()
        turtle.setheading(350)
        turtle.forward(10)
        turtle.setheading(360)
        turtle.fillcolor("yellow")
        turtle.begin_fill()
        for i in range(3):
            turtle.forward(15)
            turtle.right(120)
        turtle.end_fill()
    triangulo_pequeño()
    turtle.penup()
    turtle.goto(0,-300)
    turtle.pendown()
    turtle.hideturtle()
    turtle.write(f"Una vez en un reino geométrico de {edad} años, las figuras básicas como el círculo,\nel cuadrado y el triángulo vivían en armonía.\nEl círculo,{n}, era el líder sabio y compasivo, mientras que el cuadrado\ny el triángulo eran sus leales consejeros", False, "center", ("Arial",13))
    pass
def Dibujo_de_panel2():
    Guia()
    hexagono()
    cuadrado()
    turtle.penup()
    turtle.goto(0,-300)
    turtle.pendown()
    turtle.hideturtle()
    turtle.write(f"Sin embargo, un día, un hexágono envidioso de la perfección del círculo {n}\nconspiró para desestabilizar el reino. Convenció al\ncuadrado de que el círculo {n} no era apto para gobernar,\ny juntos tramaron un plan para derrocarlo.", False, "center", ("Arial",13))
    pass
def Dibujo_de_panel3():
    Guia()
    rec=turtle.Turtle()
    x=-200
    rec.hideturtle()
    rec.speed(50)
    for i in range(4):
        rec.penup()
        rec.goto(x,-25)
        rec.pendown()
        rec.fillcolor("red")
        rec.begin_fill()
        for i in range(2):
            rec.left(90)
            rec.forward(120)
            rec.left(90)
            rec.forward(80)
            x+=75
        rec.end_fill()
    def triangulo_pequeño():
        x=200
        y=115
        turtle.hideturtle()
        turtle.speed(50)
        turtle.penup()
        turtle.goto(x,y) 
        turtle.pendown()
        turtle.pensize(3)
        turtle.fillcolor("yellow")
        turtle.begin_fill()
        turtle.setheading(360)
        for i in range(3):
            turtle.forward(44)
            turtle.left(120)
        turtle.end_fill()
        turtle.penup()
        turtle.goto(x+11,y) 
        turtle.pendown()
        turtle.setheading(270)
        turtle.forward(15)
        for i in range(2):
            turtle.fillcolor("yellow")
            turtle.begin_fill()
            turtle.forward(5)
            turtle.right(90)
            turtle.forward(15)
            turtle.right(90)
            turtle.end_fill()
        turtle.penup()
        turtle.goto(x+33,y) 
        turtle.pendown()
        turtle.setheading(270)
        turtle.forward(15)
        for i in range(2):
            turtle.fillcolor("yellow")
            turtle.begin_fill()
            turtle.forward(5)
            turtle.left(90)
            turtle.forward(15)
            turtle.left(90)
            turtle.end_fill()
        turtle.penup()
        turtle.goto(x+9,y+15) 
        turtle.pendown()
        turtle.setheading(190)
        turtle.forward(10)
        turtle.setheading(180)
        turtle.fillcolor("yellow")
        turtle.begin_fill()
        for i in range(3):
            turtle.forward(15)
            turtle.left(120)
        turtle.end_fill()
        turtle.penup()
        turtle.goto(x+36,y+15) 
        turtle.pendown()
        turtle.setheading(350)
        turtle.forward(10)
        turtle.setheading(360)
        turtle.fillcolor("yellow")
        turtle.begin_fill()
        for i in range(3):
            turtle.forward(15)
            turtle.right(120)
        turtle.end_fill()
    triangulo_pequeño()
    def circulo_pequeño():
        i=20
        x=55
        y=110
        v=turtle.Turtle()
        v.hideturtle()
        v.speed(100)
        v.pensize(3)
        v.fillcolor(color)
        v.begin_fill()
        v.penup()
        v.goto(x,y)
        v.pendown()
        v.circle(i)
        v.end_fill()
        v.penup()
        v.goto(x-i,y+i)
        v.pendown()
        v.right(135)#315
        v.forward(15) #si le cambias lo grande le cambias este valor, solo es el largo del brazo
        v.fillcolor(color)
        v.begin_fill()
        v.circle(5)
        v.end_fill()
        v.penup()
        v.goto(x+i,y+i)
        v.pendown()
        v.left(90)
        v.forward(15)
        v.left(180)
        v.fillcolor(color)
        v.begin_fill()
        v.circle(5)
        v.end_fill()
        v.penup()
        v.setheading(270)
        v.goto(x+10,y+2)
        v.pendown()
        v.forward(15)
        v.fillcolor(color)
        v.begin_fill()
        for i in range(2):
            v.left(90)
            v.forward(15)
            v.left(90)
            v.forward(5)
        v.end_fill()
        v.penup()
        v.setheading(270)
        v.goto(x-10,y+2)
        v.pendown()
        v.forward(15)
        v.fillcolor(color)
        v.begin_fill()
        for i in range(2):
            v.right(90)
            v.forward(15)
            v.right(90)
            v.forward(5)
        v.end_fill()
    circulo_pequeño()
    def hexagono_pequeño():
        x=-225
        y=110
        t=turtle.Turtle()
        t.hideturtle()
        t.speed(50)
        t.penup()
        t.goto(x,y) 
        t.setheading(180)
        t.pendown()
        t.pensize(3)
        t.fillcolor("blue")
        t.begin_fill()
        for i in range(6):
            t.forward(25)
            t.right(60)
        t.end_fill()
        def dibujar_manos():
            t.penup()
            t.goto(x-38,y+20) 
            t.setheading(240)
            t.pendown()
            t.forward(10)
            t.fillcolor("blue")
            t.begin_fill()
            for i in range(6):
                t.forward(10)
                t.right(60)
            t.end_fill()
            t.penup()
            t.goto(x+13,y+20) 
            t.setheading(300)
            t.pendown()
            t.forward(10)
            t.fillcolor("blue")
            t.begin_fill()
            for i in range(6):
                t.forward(10)
                t.left(60)
            t.end_fill()
        dibujar_manos()
        def dibujar_pies():
            t.penup()
            t.goto(x-18,y) 
            t.pendown()
            t.setheading(270)
            t.forward(10)
            for i in range(2):
                t.fillcolor("blue")
                t.begin_fill()
                t.forward(5)
                t.right(90)
                t.forward(15)
                t.right(90)
                t.end_fill()
            t.penup()
            t.goto(x-8,y) 
            t.pendown()
            t.setheading(270)
            t.forward(10)
            for i in range(2):
                t.fillcolor("blue")
                t.begin_fill()
                t.forward(5)
                t.left(90)
                t.forward(15)
                t.left(90)
                t.end_fill() 
        dibujar_pies()
    hexagono_pequeño()
    turtle.penup()
    turtle.goto(0,-300)
    turtle.pendown()
    turtle.hideturtle()
    turtle.write("Pero antes de que pudieran actuar, el triangulo los escucho y desafio\nal hexagono a superar una serie de pruebas para demostrar su valía.\nEl concurso consistia en llegar primero al triangulo, saltando\nrectangulos uno tras otro.", False, "center", ("Arial",15))
    pass
def Dibujo_de_panel4():
    Guia()
    hexagono()
    circulo()
    def dibujar_trofeo():
        x=50
        y=0
        turtle.speed(55)
        turtle.hideturtle
        turtle.width(2)
        turtle.penup()
        turtle.goto(x,y)
        turtle.pendown()
        turtle.fillcolor("yellow")
        turtle.begin_fill()
        for i in range(2):
            turtle.forward(60)
            turtle.left(90)
            turtle.forward(40)
            turtle.left(90)
        turtle.end_fill()
        turtle.penup()
        turtle.goto(x-30,y+100)  # Posición del centro de la media luna
        turtle.pendown()
        turtle.pendown()
        turtle.color("black", "yellow")  # Bordes negros, relleno gris
        turtle.begin_fill()
        turtle.right(90)
        turtle.circle(60, 180)  # Dibujar la mitad del círculo con radio 60
        turtle.end_fill()
        turtle.left(90)
        turtle.forward(120)
    dibujar_trofeo()
    turtle.penup()
    turtle.goto(0,-300)
    turtle.pendown()
    turtle.hideturtle()
    turtle.write(f"Como se esperaba el círculo {n} demostró su gran capacidad como\nel lider de las figuras geometricas y su liderazgo y bondad fueron\npuestas a prueba, ganándose el respeto incluso del hexágono\ny perdonando su conspiración", False, "center", ("Arial",15))
    pass
def Dibujo_de_panel5():
    Guia()
    castillo()
    def circulo_pequeño():
            i=20
            x=0
            y=-100
            v=turtle.Turtle()
            v.hideturtle()
            v.speed(100)
            v.pensize(3)
            v.fillcolor(color)
            v.begin_fill()
            v.penup()
            v.goto(x,y)
            v.pendown()
            v.circle(i)
            v.end_fill()
            v.penup()
            v.goto(x-i,y+i)
            v.pendown()
            v.right(135)#315
            v.forward(15) #si le cambias lo grande le cambias este valor, solo es el largo del brazo
            v.fillcolor(color)
            v.begin_fill()
            v.circle(5)
            v.end_fill()
            v.penup()
            v.goto(x+i,y+i)
            v.pendown()
            v.left(90)
            v.forward(15)
            v.left(180)
            v.fillcolor(color)
            v.begin_fill()
            v.circle(5)
            v.end_fill()
            v.penup()
            v.setheading(270)
            v.goto(x+10,y+2)
            v.pendown()
            v.forward(15)
            v.fillcolor(color)
            v.begin_fill()
            for i in range(2):
                v.left(90)
                v.forward(15)
                v.left(90)
                v.forward(5)
            v.end_fill()
            v.penup()
            v.setheading(270)
            v.goto(x-10,y+2)
            v.pendown()
            v.forward(15)
            v.fillcolor(color)
            v.begin_fill()
            for i in range(2):
                v.right(90)
                v.forward(15)
                v.right(90)
                v.forward(5)
            v.end_fill()
    circulo_pequeño()
    def cuadrado_pequeño():
        x=-100
        y=-100
        turtle.hideturtle
        turtle.speed(50)
        turtle.penup()
        turtle.goto(x,y) 
        turtle.pendown()
        turtle.pensize(3)
        turtle.fillcolor("darkgreen")
        turtle.begin_fill()  
        turtle.setheading(90)
        for i in range(4):
            turtle.forward(40)
            turtle.left(90)
        turtle.end_fill()
        def dibujar_pies():
            turtle.penup()
            turtle.goto(x-30,y) 
            turtle.pendown()
            turtle.setheading(270)
            turtle.forward(10)
            for i in range(2):
                turtle.fillcolor("darkgreen")
                turtle.begin_fill()
                turtle.forward(5)
                turtle.right(90)
                turtle.forward(15)
                turtle.right(90)
                turtle.end_fill()
            turtle.penup()
            turtle.goto(x-10,y) 
            turtle.pendown()
            turtle.setheading(270)
            turtle.forward(10)
            for i in range(2):
                turtle.fillcolor("darkgreen")
                turtle.begin_fill()
                turtle.forward(5)
                turtle.left(90)
                turtle.forward(15)
                turtle.left(90)
                turtle.end_fill() 
        dibujar_pies()
        def dibujar_manos():
            turtle.penup()
            turtle.goto(x-40,y+20) 
            turtle.setheading(240)
            turtle.pendown()
            turtle.forward(15)
            turtle.fillcolor("darkgreen")
            turtle.begin_fill()
            for i in range(4):
                turtle.forward(8)
                turtle.right(90)
            turtle.end_fill()
            turtle.penup()
            turtle.goto(x,y+20) 
            turtle.setheading(300)
            turtle.pendown()
            turtle.forward(15)
            turtle.fillcolor("darkgreen")
            turtle.begin_fill()
            for i in range(4):
                turtle.forward(8)
                turtle.left(90)
            turtle.end_fill()
        turtle.end_fill()
        dibujar_manos()
    cuadrado_pequeño()
    def triangulo_pequeño():
        x=100
        y=-100
        turtle.hideturtle()
        turtle.speed(50)
        turtle.penup()
        turtle.goto(x,y) 
        turtle.pendown()
        turtle.pensize(3)
        turtle.fillcolor("yellow")
        turtle.begin_fill()
        turtle.setheading(360)
        for i in range(3):
            turtle.forward(44)
            turtle.left(120)
        turtle.end_fill()
        turtle.penup()
        turtle.goto(x+11,y) 
        turtle.pendown()
        turtle.setheading(270)
        turtle.forward(15)
        for i in range(2):
            turtle.fillcolor("yellow")
            turtle.begin_fill()
            turtle.forward(5)
            turtle.right(90)
            turtle.forward(15)
            turtle.right(90)
            turtle.end_fill()
        turtle.penup()
        turtle.goto(x+33,y) 
        turtle.pendown()
        turtle.setheading(270)
        turtle.forward(15)
        for i in range(2):
            turtle.fillcolor("yellow")
            turtle.begin_fill()
            turtle.forward(5)
            turtle.left(90)
            turtle.forward(15)
            turtle.left(90)
            turtle.end_fill()
        turtle.penup()
        turtle.goto(x+9,y+15) 
        turtle.pendown()
        turtle.setheading(190)
        turtle.forward(10)
        turtle.setheading(180)
        turtle.fillcolor("yellow")
        turtle.begin_fill()
        for i in range(3):
            turtle.forward(15)
            turtle.left(120)
        turtle.end_fill()
        turtle.penup()
        turtle.goto(x+36,y+15) 
        turtle.pendown()
        turtle.setheading(350)
        turtle.forward(10)
        turtle.setheading(360)
        turtle.fillcolor("yellow")
        turtle.begin_fill()
        for i in range(3):
            turtle.forward(15)
            turtle.right(120)
        turtle.end_fill()
    triangulo_pequeño()
    hexagono_pequeño()
    turtle.penup()
    turtle.goto(0,50)
    turtle.pendown()
    turtle.left(90)
    turtle.forward(100)
    turtle.fillcolor("white")
    turtle.begin_fill()
    for i in range(3):
        turtle.left(120)
        turtle.forward(60)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(0,-300)
    turtle.pendown()
    turtle.hideturtle()
    turtle.write("Al final, el reino geométrico emergió más unido que nunca,\nrecordando que la verdadera fuerza radica en la diversidad y\nla colaboración.", False, "center", ("Arial",15))
    pass
def Cuento_Completo():
    def pasar_hoja():
        input("Presiona Enter para continuar")
    turtle.clear()
    Dibujo_de_panel1()
    pasar_hoja()
    turtle.clear()
    Dibujo_de_panel2()
    pasar_hoja()
    turtle.clear()
    Dibujo_de_panel3()
    pasar_hoja()
    turtle.clear()
    Dibujo_de_panel4()
    pasar_hoja()
    turtle.clear()
    Dibujo_de_panel5()
    pasar_hoja()
n=str(input("¡Ingresa tu primer nombre!: "))
print("¡Hola", n, "Este es un cuento de figuras geometricas para que puedas aprender a reconocerlas.")
edad=int(input("Dime, ¿Cuál es tu edad?:\n"))
print("Perfecto! Tu edad es ", edad)
colores=["red","blue","yellow","green","orange","pink"]
while True:
    color=str(input("Ahora, dime tu color favorito entre estas selecciones: red, blue, yellow, green, orange, pink\n"))
    if color not in colores:
        print("Vuelve a escribir un color por favor, trata de escribirlo adecuadamente")
    else:
        print("Perfecto! tu color favorito es", color)
        break
turtle.setup(700,700)
while True:
    SeleccionDeMenu=["cuento","dibujo","salir"]
    SeleccionDeMenu=str(input("Para seleccionar que hacer con tu cuento, por favor escribe:\n1.'cuento' para ver todo el cuento\n2.'dibujo' para ver un dibujo del cuento\n3.'salir' para decirle adios al cuento por ahora\n"))
    if SeleccionDeMenu=="cuento":
        print("Ahora visualizaras el cuento que realizamos para ti! Recuerda salir de la ventana para pasar hoja en tu cuento")
        Cuento_Completo()
    elif SeleccionDeMenu=="dibujo":
        dibujo=int(input("Entendido Camarada!\n¿Que dibujo del cuento deseas ver? (Puedes elegir opciones del 1 al 5, presiona cualquier otro número para salir de este menú)"))
        if dibujo==1:
            turtle.reset()
            Dibujo_de_panel1()
        elif dibujo==2:
            turtle.reset()
            Dibujo_de_panel2()
        elif dibujo==3:
            turtle.reset()
            Dibujo_de_panel3()
        elif dibujo==4:
            turtle.reset()
            Dibujo_de_panel4()
        elif dibujo==5:
            turtle.reset()
            Dibujo_de_panel5()
        else:
            break
    elif SeleccionDeMenu=="salir":
        print("Gracias por tu atención! Hasta pronto!")
        break
    else:
        print("Por favor, intenta escribir correctamente la opcion")
